### ISSUE TITLE
`cloudwatch_log_group_retention_in_days` in `container_definition_defaults` never honoured; per-container default 14 always wins

### ISSUE THREAD

**Issue by sassdavid** [terraform-aws-modules/terraform-aws-ecs#305]
## Description

`container_definitions` sets

```hcl
cloudwatch_log_group_retention_in_days = optional(number, 14)
```

The service code resolves the value with

```hcl
cloudwatch_log_group_retention_in_days = try(coalesce(each.value.cloudwatch_log_group_retention_in_days, var.container_definition_defaults.cloudwatch_log_group_retention_in_days), null)
```

## Versions

- Module version [Required]: 6.0.1

- Terraform version: 1.12.2

- Provider version(s): 6.2.0

## Reproduction Code [Required]

Try using `container_definition_defaults` without defining `cloudwatch_log_group_retention_in_days` at the container level.

```hcl
container_definition_defaults = {
  cloudwatch_log_group_retention_in_days = 7
}
```

## Expected behavior

Containers that don’t set the field individually should inherit the value from `container_definition_defaults`.

## Actual behavior

Because the `optional(..., 14)` default is injected into every `each.value`, `coalesce` always returns 14 – any value provided through `container_definition_defaults` is ignored.

## Additional context

It is likely that several other variables are also affected, indicating the need for a global solution.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.2 :tada:

**Comment by sassdavid** [comment]
Hi,

Thank you for the quick fix, @bryantbiggs. Unfortunately, it still doesn't work for me.

When I set `cloudwatch_log_group_retention_in_days` to 7 in `container_definition_defaults`, the new module version (6.0.2) reverts it to the default value of 14.
The same issue occurs with `readonlyRootFilesystem` inside `container_definition_defaults`.

Currently, most of the default values are applied to the `container_definitions` variable. Shouldn't we be using them in `container_definition_defaults` instead?

**Comment by bryantbiggs** [comment]
I'll take another look today - these variable optional attributes are really a pain in the a$$

**Comment by bryantbiggs** [comment]
ya I don't think the variable overloading lookup with `*_defaults` is going to work in a world with variable optional attributes. which in this case isn't awful, its not common to more than 2 container definitions per task so the `*_defaults` is a "nice to have". but it looks like we'll need to remove that since its not going to work as advertised 

https://github.com/bryantbiggs/terraform-awful-variable-optional-attributes

**Comment by sassdavid** [comment]
Thank you so much for this type of investigation and for experimenting with these kinds of attributes.

Basically, yes, I agree—let's remove it, and we'll have a clear direction. 🙂

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.4 :tada:
